include $(MAKE_INCLUDE_DIR)/config.mk

include $(MAKERULES_DIR)/common.mk
include $(MAKEFILES_DIR)/$(MODULE_NAME).mk

MODULE_PATH?=$(SOURCE_DIR)/$(MODULE_BASE_DIR)
MODULE_SOURCE_PATH?=$(MODULE_PATH)/src
MODULE_HEADERS_PATH?=$(MODULE_PATH)/include
HEADERS_EXPORT_PATH?=$(INCLUDE_DIR)/$(MODULE_HEADERS_EXPORT_DIR)
