#!/bin/bash

usage() {
    echo "Usage: $0 <header to export> <target>"
}

if test $# -lt 2
then
    usage
    exit 1
fi

HEADER="$1"
TARGET="$2"

PATH=$(realpath --relative-to="$(dirname $TARGET)" "$HEADER")

echo -e "#pragma once\n\n#include \"$PATH\"" > "$TARGET"
